services:

  cli:
    container_name: cli
    build:
      context: ./docker/cli
      dockerfile: Dockerfile
      args:
        PHP_VERSION: ${PHP_VERSION:-}
        COMPOSER_VERSION: ${COMPOSER_VERSION:+ --version=${COMPOSER_VERSION}}
        NODE_VERSION: ${NODE_VERSION:-lts}
    user: ${CUID:-0}:${CGID:-0}
    restart: unless-stopped
    environment:
      TZ: ${TZ}
    volumes:
      - type: bind
        source: ./project
        target: /project
    networks:
      - php-docker-dev-env

  php-fpm:
    container_name: php-fpm
    build:
      context: ./docker/php-fpm
      dockerfile: Dockerfile
      args:
        PHP_VERSION: ${PHP_VERSION:+${PHP_VERSION}-}
        XDEBUG_VERSION: ${XDEBUG_VERSION:+-${XDEBUG_VERSION}}
    user: ${CUID:-0}:${CGID:-0}
    restart: unless-stopped
    environment:
      PHP_IDE_CONFIG: "serverName=${IDE_SERVER_NAME:-php-docker-dev-env}"
    volumes:
      - type: bind
        source: ./project
        target: /project
      - type: bind
        source: ./docker/xdebug/xdebug.ini
        target: /usr/local/etc/php/conf.d/xdebug.ini
      - type: bind
        source: ./docker/xdebug/logs
        target: /xdebug-logs
    networks:
      - php-docker-dev-env
    extra_hosts:
      host.docker.internal: host-gateway

  nginx:
    container_name: nginx
    image: nginx:latest
    restart: unless-stopped
    ports:
      - "8080:80"
    depends_on:
      - php-fpm
    volumes:
      - type: bind
        source: ./project
        target: /project
      - type: bind
        source: ./docker/nginx/conf.d
        target: /etc/nginx/conf.d
    networks:
      - php-docker-dev-env

  postgres:
    container_name: postgres
    image: postgres:latest
    restart: unless-stopped
    ports:
      - "8432:5432"
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres-root-password
      POSTGRES_DB: project
      POSTGRES_USER: root
      TZ: ${TZ}
    secrets:
      - postgres-root-password
    volumes:
      - php-docker-dev-env-postgres-data:/var/lib/postgresql
    networks:
      - php-docker-dev-env

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    ports:
      - "8090:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@admin.com}
      PGADMIN_DEFAULT_PASSWORD_FILE: /run/secrets/pgadmin-admin-password
      PGPASSFILE: /run/secrets/pgadmin-pgpass
      TZ: ${TZ}
    secrets:
      - pgadmin-admin-password
      - pgadmin-pgpass
    volumes:
      - type: bind
        source: ./docker/pgadmin/servers.json
        target: /pgadmin4/servers.json
    depends_on:
      - postgres
    networks:
      - php-docker-dev-env

  production:
    build:
      context: .
      dockerfile: ./docker/build-app/production.Dockerfile
      args:
        PHP_VERSION: ${PHP_VERSION:+${PHP_VERSION}-}
    profiles:
      - production

  stand-alone:
    build:
      context: .
      dockerfile: ./docker/build-app/stand-alone.Dockerfile
      args:
        PHP_VERSION: ${PHP_VERSION:+${PHP_VERSION}-}
    profiles:
      - stand-alone

secrets:
  postgres-root-password:
    file: ./docker/secrets/postgres_root_password.txt
  pgadmin-admin-password:
    file: ./docker/secrets/pgadmin_admin_password.txt
  pgadmin-pgpass:
    file: ./docker/secrets/pgadmin_pgpass.txt

volumes:
  php-docker-dev-env-postgres-data:
    name: php-docker-dev-env-postgres-data

networks:
  php-docker-dev-env:
    name: php-docker-dev-env
    driver: bridge